//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MKSHARED.RC
//
#define IDD_MAIN                        100
#define IDI_MKSHARED                    101
#define IDC_CARD32                      1000
#define IDC_CARD128                     1001
#define IDC_CARD256                     1002
#define IDC_CARD512                     1003
#define IDC_CARD1024                    1004
#define IDC_CARD2048                    1005
#define IDC_CARD4096                    1006
#define IDC_STATIC_TITLE                1007
#define IDC_FILENAME                    1008
#define IDC_FILE_SIZE                   1009
#define IDC_NO_OF_PORTS                 1010
#define IDC_PORT_NO                     1011
#define IDC_RESULT                      1012
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1013
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
